# Generated by Django 5.2.6 on 2025-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_hectarepatronage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='new_feedback_requests_receiver_emails',
            field=models.TextField(default='vlad.buklovsky@gmail.com', help_text='Почты тех, кому будет отправлено уведомление о новой заявке, раздёлённые знаком запятой ",".'),
        ),
    ]
