# Generated by Django 5.2.6 on 2025-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessconfig_new_feedback_requests_receiver_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hectarepatronagebonus',
            options={'verbose_name': 'бонус', 'verbose_name_plural': 'бонусы шефства над гектарами'},
        ),
        migrations.RemoveField(
            model_name='hectarepatronagebonus',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hectarepatronagebonus',
            name='service',
        ),
        migrations.AddField(
            model_name='hectarepatronage',
            name='bonuses',
            field=models.ManyToManyField(to='business.hectarepatronagebonus', verbose_name='Бонусы'),
        ),
    ]
