# Generated by Django 5.2.6 on 2025-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_hectarepatronagebonus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hectarepatronagebonus',
            options={'ordering': ['order'], 'verbose_name': 'бонус', 'verbose_name_plural': 'бонусы шефства над гектарами'},
        ),
        migrations.AddField(
            model_name='hectarepatronagebonus',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
