# Generated by Django 5.2.6 on 2025-11-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_hectarepatronagebonus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hectarepatronage',
            options={'ordering': ['hectares'], 'verbose_name': 'шефство гектара', 'verbose_name_plural': 'варианты шефства гектаров'},
        ),
        migrations.RemoveField(
            model_name='hectarepatronage',
            name='order',
        ),
    ]
