# Generated by Django 5.2.6 on 2025-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_hectarepatronage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='debug_email_sending_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
